tasks:
#  - command: pip3 install -U platformio && platformio run -e d1_mini
- init: pip install esptool
- command: pip3 install -U platformio && platformio run && cp ./.pio/build/heltec_wifi_lora_32_V2/firmware.bin ./docs/test.bin

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Atishay-Jain.All-Autocomplete
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
